import { describe, expect, it } from "vitest";
import { briefSchema, evidenceLinkSchema, interviewConsentSchema, planRevisionRequestSchema, projectInputSchema, researchPlanSchema, surveySubmissionSchema } from "@/lib/schemas";

describe("critical research workflow contracts",()=>{
  it("validates project creation",()=>expect(projectInputSchema.parse({businessQuestion:"Which market should we enter next?",businessDescription:"A regional service business considering expansion.",industry:"Services",geography:"Singapore",researchMode:"primary_secondary"})).toBeTruthy());
  it("validates a structured plan",()=>expect(researchPlanSchema.parse({decisionStatement:"Choose A or B",objectives:["Understand demand","Compare risks"],hypotheses:["A is stronger"],secondaryWorkstreams:[{title:"Market",evidenceExpected:["Size"]}],evidenceGaps:["Preference"],primaryMethodology:"Survey",targetRespondents:"Customers",sampleSizeRecommendation:"n=150",timeline:"2 weeks",estimatedOperationalCosts:"S$3k",deliverables:["Brief"],limitations:["Sample"]})).toBeTruthy());
  it("normalizes list-shaped respondent groups into the plan string contract",()=>{const plan=researchPlanSchema.parse({decisionStatement:"Choose A or B",objectives:["Understand demand","Compare risks"],hypotheses:["A is stronger"],secondaryWorkstreams:[{title:"Market",evidenceExpected:"Market size"}],evidenceGaps:"Unknown retention",primaryMethodology:"Survey",targetRespondents:["Office workers","Nearby residents"],sampleSizeRecommendation:"n=150",timeline:"2 weeks",estimatedOperationalCosts:"To be estimated",deliverables:["Brief"],limitations:["Sample"]});expect(plan.targetRespondents).toBe("Office workers; Nearby residents");expect(plan.evidenceGaps).toEqual(["Unknown retention"]);expect(plan.secondaryWorkstreams[0].evidenceExpected).toEqual(["Market size"])});
  it("accepts uncertainty in consultation answers as project context",()=>expect(projectInputSchema.passthrough().parse({businessQuestion:"Which location should we choose next?",businessDescription:"A coffee business comparing two location types.",industry:"Food and beverage",geography:"Singapore",researchMode:"primary_secondary",clarifyingAnswers:[{question:"What is the rent threshold?",answer:"I don't know"}]})).toBeTruthy());
  it("validates a client revision request without asking the client to prescribe methodology",()=>{const currentPlan=researchPlanSchema.parse({decisionStatement:"Choose A or B",objectives:["Understand demand","Compare risks"],hypotheses:["A is stronger"],secondaryWorkstreams:[{title:"Market",evidenceExpected:["Size"],rationale:"Size frames the opportunity"}],evidenceGaps:["Preference"],primaryMethodology:"Survey",primaryRationale:"Direct evidence resolves preference",targetRespondents:"Customers",sampleSizeRecommendation:"n=150",timeline:"2 weeks",estimatedOperationalCosts:"S$3k",costBreakdown:{currency:"S$",items:[{category:"Secondary research",description:"AI-led evidence review",amount:300,basis:"Model and verification usage"}],total:300,assumptions:["Estimate only"]},deliverables:["Brief"],limitations:["Sample"]});const request=planRevisionRequestSchema.parse({currentPlan,revisionRequest:{budgetPreference:"reduce",timingPreference:"maintain",businessPriorities:"Keep the location decision as the priority",scopeTradeoffs:"Less detail on positioning"}});expect(request.revisionRequest).not.toHaveProperty("methodology");expect(request.revisionRequest.budgetPreference).toBe("reduce")});
  it("requires survey consent",()=>expect(()=>surveySubmissionSchema.parse({token:"northstar-demo",consent:false,answers:{q1:"Monthly"}})).toThrow());
  it("accepts consented survey submission",()=>expect(surveySubmissionSchema.parse({token:"northstar-demo",consent:true,answers:{q1:"Monthly"}})).toBeTruthy());
  it("requires interview consent",()=>expect(interviewConsentSchema.parse({token:"northstar-jamie",consent:true,disclosureVersion:"v1"})).toBeTruthy());
  it("links every claim to typed evidence",()=>expect(evidenceLinkSchema.parse({claimId:"C1",evidenceType:"survey_result",evidenceId:"Q2"})).toBeTruthy());
  it("validates final brief generation",()=>expect(briefSchema.parse({executiveRecommendation:"Choose A",rationale:["Evidence"],risks:["Cost"],changeConditions:["If B costs less"],nextActions:["Validate"],evidenceLinks:[{claimId:"C1",evidenceType:"source",evidenceId:"S01"}]})).toBeTruthy());
});
