"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import { AgentAvatar } from "@/components/agent-avatar";
import { Badge } from "@/components/ui";
import { Send, ShieldCheck, StopCircle } from "lucide-react";

type Message={speaker:"Daniel"|"You";text:string};
const guide=["Recent cinema visit and venue choice","Effect of travel time","Heartland versus city-centre preference","Conditions that would change the preference"];

export function InterviewExperience(){
  const params=useParams<{publicToken:string}>(); const [started,setStarted]=useState(false); const [consent,setConsent]=useState(false); const [draft,setDraft]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [done,setDone]=useState(false); const [error,setError]=useState(""); const [thinking,setThinking]=useState(false);
  async function begin(){setError("");const response=await fetch("/api/interview-consent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:params.publicToken,consent:true,disclosureVersion:"v1"})});if(response.ok)setStarted(true);else setError("We could not record consent. Please try again.")}
  async function submit(){if(!draft.trim()||thinking)return;const next=[...messages,{speaker:"You" as const,text:draft}];setMessages(next);setDraft("");setThinking(true);setError("");try{const response=await fetch("/api/interview-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:params.publicToken,messages:next,approvedGuide:guide})});const result=await response.json() as {message?:string;complete?:boolean;error?:string};if(!response.ok)throw new Error(result.error);setMessages([...next,{speaker:"Daniel",text:result.message??"Thank you. Could you tell me more?"}]);setDone(Boolean(result.complete))}catch{setError("Daniel could not respond just now. Your answer remains in this browser; please retry.")}finally{setThinking(false)}}
  if(!started)return <main className="app-page"><div className="interview-shell"><div className="panel" style={{padding:40}}><div style={{display:"flex",gap:16,alignItems:"center"}}><AgentAvatar slug="daniel-wong" size="lg"/><div><Badge tone="coral">AI interviewer</Badge><h1 style={{font:"500 45px/1 var(--font-serif)",margin:"12px 0"}}>A conversation about cinema choices</h1></div></div><p style={{lineHeight:1.7}}>I’m Daniel, an AI research agent for Field & Signal. This demonstration interview explores how people choose cinema locations. It takes about 8–10 minutes and will be transcribed in this browser session.</p><div className="consent-box"><ShieldCheck color="var(--teal)"/><h3>Your choice, throughout</h3><p>You may skip any question or stop at any time. Please do not include sensitive personal information.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I am 18 or older, understand the AI disclosure, and consent to participate and be transcribed.</label></div>{error&&<p role="alert" style={{color:"var(--coral)"}}>{error}</p>}<button disabled={!consent} className="button button-primary" style={{marginTop:20,opacity:consent?1:.5}} onClick={begin}>Begin interview</button></div></div></main>;
  return <main className="app-page"><div className="interview-shell"><header style={{display:"flex",alignItems:"center",gap:13,marginBottom:20}}><AgentAvatar slug="daniel-wong"/><div><Badge tone="coral">Daniel Wong · AI interviewer</Badge><h2 style={{margin:"7px 0 0"}}>Cinema location study</h2></div><button className="button button-secondary" onClick={()=>setDone(true)} style={{marginLeft:"auto"}}><StopCircle size={16}/> Stop</button></header><section className="panel transcript"><div className="message"><AgentAvatar slug="daniel-wong" size="sm"/><p>When did you last visit a cinema, and what shaped your choice of venue?</p></div>{messages.map((m,i)=>m.speaker==="You"?<div className="message respondent" key={i}><p>{m.text}</p></div>:<div className="message" key={i}><AgentAvatar slug="daniel-wong" size="sm"/><p>{m.text}</p></div>)}{error&&<p role="alert" style={{color:"var(--coral)"}}>{error}</p>}{done?<div className="notice"><strong>Interview complete.</strong><br/>Thank you. In a configured Supabase workspace, the timestamped transcript and concise summary are persisted for analysis.</div>:<div style={{display:"flex",gap:10,marginTop:24}}><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} aria-label="Interview response" placeholder="Type your response—or say “skip”" style={{flex:1,padding:13,border:"1px solid var(--line)",borderRadius:10}}/><button disabled={thinking} className="button button-primary" onClick={submit}>{thinking?"…":<Send size={16}/>}</button></div>}</section></div></main>
}
