"use client";

import { useEffect, useRef, useState } from "react";
import { AgentAvatar } from "@/components/agent-avatar";
import { Badge, Progress } from "@/components/ui";
import { CheckCircle2, Keyboard, Mic, Pause, Play, Send, ShieldCheck, SkipForward, StopCircle, Volume2 } from "lucide-react";

type Message = { speaker: "Daniel" | "You"; text: string };
type State = "ready" | "speaking" | "listening" | "transcribing" | "thinking" | "complete";
export function InterviewExperience({ token, study }: { token: string; study: { title: string; introduction: string; firstQuestion: string; participantName: string; demo: boolean } }) {
  const [started, setStarted] = useState(false); const [consent, setConsent] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState(""); const [state, setState] = useState<State>("ready"); const [error, setError] = useState(""); const [textMode, setTextMode] = useState(false); const [coverage, setCoverage] = useState(8);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const question = messages.filter((m) => m.speaker === "Daniel").at(-1)?.text ?? study.firstQuestion;
  function speak(text: string) { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate = .96; utterance.pitch = .92; utterance.onstart = () => setState("speaking"); utterance.onend = () => setState("ready"); window.speechSynthesis.speak(utterance); }
  useEffect(() => () => { if (typeof window !== "undefined") window.speechSynthesis?.cancel(); recorder.current?.stream.getTracks().forEach((track) => track.stop()); }, []);
  async function begin() { setError(""); const response = await fetch("/api/interview-consent", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, consent: true, disclosureVersion: "v2-assisted-voice", retainAudio: false }) }); const result = await response.json(); if (!response.ok) return setError(result.error ?? "Could not record consent"); setStarted(true); setMessages([{ speaker: "Daniel", text: study.firstQuestion }]); setTimeout(() => speak(study.firstQuestion), 200); }
  async function startRecording() { try { window.speechSynthesis.cancel(); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const media = new MediaRecorder(stream); chunks.current = []; media.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; media.onstop = async () => { stream.getTracks().forEach((track) => track.stop()); setState("transcribing"); const file = new File(chunks.current, "answer.webm", { type: media.mimeType || "audio/webm" }); const form = new FormData(); form.append("audio", file); try { const response = await fetch("/api/interview-transcribe", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setDraft(result.text); setTextMode(true); setState("ready"); } catch (e) { setError(e instanceof Error ? e.message : "Transcription failed"); setTextMode(true); setState("ready"); } }; recorder.current = media; media.start(); setState("listening"); } catch { setError("Microphone access was not available. You can type the response instead."); setTextMode(true); setState("ready"); } }
  function stopRecording() { if (recorder.current?.state === "recording") recorder.current.stop(); }
  async function send(answer = draft, stopping = false) { if (!answer.trim() && !stopping) return; setState("thinking"); setError(""); if (answer.trim()) setMessages((current) => [...current, { speaker: "You", text: answer.trim() }]); setDraft(""); try { const response = await fetch("/api/interview-message", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, answer: answer.trim() || undefined, stopping }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessages((current) => [...current, { speaker: "Daniel", text: result.message }]); setCoverage(result.guideCoverage ?? Math.min(100, coverage + 12)); if (result.complete) setState("complete"); else { setState("ready"); setTextMode(false); setTimeout(() => speak(result.message), 100); } } catch (e) { setError(e instanceof Error ? e.message : "Daniel could not continue"); setState("ready"); setTextMode(true); } }
  if (!started) return <main className="app-page"><div className="interview-shell"><section className="panel interview-consent"><div className="agent-inline"><AgentAvatar slug="daniel-wong" size="lg"/><div><Badge tone="coral">Daniel Wong · AI-assisted interviewer</Badge><h1>{study.title}</h1></div></div><p>{study.introduction}</p><div className="consent-box"><ShieldCheck/><h3>Your choice, throughout</h3><p>Daniel will speak each question and transcribe each recorded answer. Raw turn audio is sent for transcription and is not retained by Field & Signal. You can review the transcript, type instead, skip, pause or stop.</p><label><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)}/> I am 18 or older and consent to this AI-assisted, transcribed research interview.</label></div>{error && <p className="form-error">{error}</p>}<button className="button button-primary" disabled={!consent} onClick={begin}>Begin interview <Play size={17}/></button></section></div></main>;
  return <main className="app-page"><div className="interview-shell"><header className="interview-header"><div className="agent-inline"><AgentAvatar slug="daniel-wong"/><div><Badge tone="coral">Daniel · AI-assisted interviewer</Badge><h2>{study.title}</h2></div></div><button className="button button-secondary" onClick={() => send("", true)}><StopCircle size={16}/> Stop</button></header><div className="interview-status"><span>{state === "speaking" ? "Daniel is speaking" : state === "listening" ? "Listening to the participant" : state === "transcribing" ? "Transcribing the answer" : state === "thinking" ? "Daniel is deciding what to ask next" : state === "complete" ? "Interview complete" : "Ready for the participant"}</span><Progress value={coverage}/></div><section className="panel voice-interview"><div className={`voice-orb ${state}`}><AgentAvatar slug="daniel-wong" size="lg"/>{state === "listening" && <i/>}</div><Badge>{study.demo ? "Practice session · excluded from evidence" : `Participant: ${study.participantName}`}</Badge><h1>{state === "complete" ? "Thank you for your time." : question}</h1>{state !== "complete" && <button className="listen-again" onClick={() => speak(question)}><Volume2 size={16}/> Hear question again</button>}{messages.length > 1 && <details className="transcript-review"><summary>Review conversation transcript</summary>{messages.map((message, index) => <p key={index} className={message.speaker === "You" ? "participant-line" : "daniel-line"}><strong>{message.speaker}:</strong> {message.text}</p>)}</details>}{error && <p className="form-error">{error}</p>}{state === "complete" ? <div className="completion-inline"><CheckCircle2/><p>The confirmed transcript is ready for Sofia’s analysis. {study.demo && "Because this is practice, it will not be included as research evidence."}</p></div> : state === "listening" ? <button className="record-button recording" onClick={stopRecording}><Pause/> Finish answer</button> : state === "transcribing" || state === "thinking" || state === "speaking" ? <div className="voice-working"><span/><span/><span/></div> : textMode ? <div className="transcript-editor"><label>Review or correct the transcript<textarea value={draft} onChange={(e) => setDraft(e.target.value)} rows={4} autoFocus/></label><div><button className="button button-secondary" onClick={() => setTextMode(false)}><Mic size={16}/> Record again</button><button className="button button-primary" onClick={() => send()} disabled={!draft.trim()}>Confirm answer <Send size={16}/></button></div></div> : <div className="voice-actions"><button className="record-button" onClick={startRecording}><Mic/> Record answer</button><button onClick={() => setTextMode(true)}><Keyboard/> Type instead</button><button onClick={() => send("skip") }><SkipForward/> Skip</button></div>}</section></div></main>;
}
