"use client";

import { useCallback, useEffect, useState } from "react";
import { AgentAvatar } from "@/components/agent-avatar";
import { PageShell } from "@/components/page-shell";
import { Badge, Button, Progress } from "@/components/ui";
import { BarChart3, Check, CheckCircle2, Copy, ExternalLink, Mic, Plus, ShieldCheck, Sparkles } from "lucide-react";

type Guide = { title: string; introduction: string; objectives: string[]; questions: { question: string; rationale: string; probes: string[] }[] };
type Snapshot = { instrument?: { interviewGuide?: Guide; guideApprovedAt?: string | null }; participants: { id: string; name: string; status: string; consent_source?: string; interviewUrl: string; interviewPath?: string }[]; interviews: { participant_id: string; status: string; summary?: string }[] };
const sample: Snapshot = { instrument: { guideApprovedAt: "sample", interviewGuide: { title: "Cinema choice and location trade-offs", introduction: "Understand the occasions and practical trade-offs behind venue choice.", objectives: ["Explain location choice", "Understand repeat-visit conditions", "Identify decision-changing trade-offs"], questions: [{ question: "Tell me about your most recent cinema visit.", rationale: "Grounds the discussion in observed behaviour.", probes: ["Why that venue?", "Who were you with?"] }, { question: "How did travel time affect the choice?", rationale: "Tests the role of access and convenience.", probes: ["What would have been too far?"] }, { question: "When would you prefer a city-centre venue over a heartland venue?", rationale: "Makes the central trade-off concrete.", probes: ["Does the occasion change that?"] }] } }, participants: [{ id: "demo", name: "Practice participant", status: "practice", consent_source: "practice session", interviewUrl: "/interview/northstar-jamie" }], interviews: [] };

function browserHostedUrl(url: string, path?: string) {
  if (typeof window === "undefined") return url;
  try {
    const publicPath = path || new URL(url, window.location.origin).pathname;
    return new URL(publicPath, window.location.origin).toString();
  } catch {
    return url;
  }
}

export function InterviewsWorkspace({ demo }: { demo: boolean }) {
  const [data, setData] = useState<Snapshot | null>(demo ? sample : null);
  const [busy, setBusy] = useState<"approve" | "create" | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState("");
  const load = useCallback(async () => { if (demo) return; const response = await fetch("/api/fieldwork/status", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }, [demo]);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function approveGuide() { setBusy("approve"); setError(""); try { const response = await fetch("/api/fieldwork/approve-guide", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not approve guide"); } finally { setBusy(null); } }
  async function create(practice: boolean) { if (demo) return window.open("/interview/northstar-jamie", "_blank"); setBusy("create"); setError(""); try { const response = await fetch("/api/fieldwork/participants", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ practice }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load(); window.open(browserHostedUrl(result.interviewUrl, result.interviewPath), "_blank"); } catch (e) { setError(e instanceof Error ? e.message : "Could not start interview"); } finally { setBusy(null); } }
  async function copy(url: string) { await navigator.clipboard.writeText(url); setCopied(url); setTimeout(() => setCopied(""), 1500); }
  if (!data) return <PageShell eyebrow="Primary research" title="Opening Daniel’s interview room." description="Loading the approved interview guide and consented sessions."><section className="panel research-loading"><AgentAvatar slug="daniel-wong" size="lg"/><Progress value={36}/></section></PageShell>;
  const guide = data.instrument?.interviewGuide;
  const approved = Boolean(data.instrument?.guideApprovedAt);
  const completed = data.interviews.filter((interview) => interview.status === "complete" && !data.participants.find((participant) => participant.id === interview.participant_id)?.consent_source?.includes("practice")).length;
  return <PageShell eyebrow={demo ? "Sample engagement · Assisted interview" : "Primary research · Assisted voice interviews"} title="Bring Daniel into the room." description="Daniel speaks the approved questions, records one answer at a time, creates a reviewable transcript and adapts his next question to what the participant actually said." actions={guide ? <Button href="/projects/live/analysis"><BarChart3 size={17}/> Continue to analysis</Button> : undefined}>
    {error && <div className="notice form-error">{error}</div>}
    {!guide ? <section className="panel fieldwork-empty"><AgentAvatar slug="daniel-wong" size="lg"/><h2>The interview guide has not been generated yet.</h2><p>Open Survey and ask Aisha to generate the primary-research instruments first.</p></section> : <>
      <div className="grid-4"><div className="metric"><strong>{data.participants.length}</strong><span>Sessions created</span></div><div className="metric"><strong>{completed}</strong><span>Research interviews complete</span></div><div className="metric"><strong>{guide.questions.length}</strong><span>Guide topics</span></div><div className="metric"><strong>0</strong><span>Raw recordings retained</span><small>Transcript-first by default</small></div></div>
      <div className="dashboard-grid"><section className="panel instrument-panel"><div className="panel-header"><div className="agent-inline"><AgentAvatar slug="daniel-wong"/><div><Badge tone="coral">Daniel · AI-assisted interviewer</Badge><h2>{guide.title}</h2></div></div><Badge tone={approved ? "default" : "gold"}>{approved ? "Approved guide" : "Awaiting approval"}</Badge></div><p className="muted-copy instrument-introduction">{guide.introduction}</p><div className="guide-objectives">{guide.objectives.map((objective) => <div key={objective}><CheckCircle2 size={17}/><span>{objective}</span></div>)}</div>{guide.questions.map((item, index) => <article className="guide-question" key={item.question}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.question}</h3><div className="guide-rationale"><strong>Why it matters</strong><p>{item.rationale}</p></div>{item.probes?.length ? <div className="probe-list"><strong>Possible probes</strong><div>{item.probes.map((probe) => <span key={probe}>{probe}</span>)}</div></div> : null}</div></article>)}</section>
        <aside>{!approved && <section className="panel approval-panel"><ShieldCheck/><h2>Approve the guide</h2><p>Daniel cannot create a research interview until you approve these objectives and guardrails. Practice mode remains available for testing.</p><button className="button button-primary full-button" disabled={Boolean(busy)} onClick={approveGuide}>{busy === "approve" ? "Approving…" : "Approve interview guide"}</button></section>}<section className="panel" style={{marginTop: approved ? 0 : 20}}><Mic/><h2>Start an interview</h2><p>Use practice mode to test Daniel without adding evidence, or create a real consented session.</p><button className="button button-primary full-button" disabled={Boolean(busy) || !approved} onClick={() => create(false)}><Plus size={16}/>{busy === "create" ? "Creating…" : "Start research interview"}</button><button className="button button-secondary full-button" onClick={() => create(true)}><Sparkles size={16}/> Practice with Daniel</button></section><section className="panel" style={{marginTop:20}}><ShieldCheck/><h2>Interview guardrails</h2><ul className="guardrail-list"><li>AI identity and transcription disclosed</li><li>One question at a time</li><li>Participant can correct the transcript</li><li>Skip, pause and stop respected</li><li>Raw audio not retained by default</li></ul></section></aside></div>
      <section className="panel interview-sessions"><div className="panel-header"><h2>Interview sessions</h2><Badge>{data.participants.length} created</Badge></div>{data.participants.length === 0 ? <p className="muted-copy">No sessions yet. Start with a practice interview to hear Daniel in action.</p> : data.participants.map((participant) => { const interview = data.interviews.find((item) => item.participant_id === participant.id); const interviewUrl = browserHostedUrl(participant.interviewUrl, participant.interviewPath); return <div className="session-row" key={participant.id}><AgentAvatar slug="daniel-wong" size="sm"/><div><strong>{participant.name}</strong><span>{participant.consent_source?.includes("practice") ? "Practice · excluded from analysis" : interview?.summary ?? "Research session"}</span></div><Badge tone={interview?.status === "complete" ? "default" : "gold"}>{interview?.status ?? participant.status}</Badge><button onClick={() => copy(interviewUrl)} aria-label="Copy interview link">{copied === interviewUrl ? <Check/> : <Copy/>}</button><a href={interviewUrl} target="_blank" rel="noreferrer" aria-label="Open interview"><ExternalLink/></a></div>; })}</section>
    </>}
  </PageShell>;
}
