"use client";

import { useEffect, useState } from "react";
import { PageShell } from "@/components/page-shell";
import { Badge, Button, Progress } from "@/components/ui";
import { CheckCircle2, GripVertical, Save } from "lucide-react";

type Question = { id: string; type: string; question: string; options_json?: string[]; required: boolean; position: number };
export function SurveyEditor({ projectId }: { projectId: string }) {
  const [survey, setSurvey] = useState<{ title: string; introduction: string; status: string } | null>(null); const [questions, setQuestions] = useState<Question[]>([]); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/fieldwork/status", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setSurvey(result.survey); setQuestions(result.questions); }).catch((e) => setError(e.message)); }, []);
  async function save() { if (!survey) return; setBusy(true); setError(""); setSaved(false); try { const response = await fetch("/api/fieldwork/survey", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: survey.title, introduction: survey.introduction, questions: questions.map((question) => ({ id: question.id, question: question.question, required: question.required, options: question.options_json ?? [] })) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "Could not save survey"); } finally { setBusy(false); } }
  if (!survey) return <PageShell eyebrow="Survey editor" title="Loading Aisha’s questionnaire." description="Client edits stay within the approved instrument structure."><section className="panel research-loading"><Progress value={35}/>{error && <p className="form-error">{error}</p>}</section></PageShell>;
  return <PageShell eyebrow="Client review · Draft questionnaire" title="Refine the language, preserve the method." description="You can improve wording, answer choices and required fields. Regenerate the instruments if the research objective itself needs to change." actions={<Button href={`/projects/${projectId}/survey`} variant="secondary">Return to survey</Button>}><section className="panel survey-editor"><label>Survey title<input value={survey.title} onChange={(e) => setSurvey({ ...survey, title: e.target.value })}/></label><label>Respondent introduction<textarea rows={4} value={survey.introduction} onChange={(e) => setSurvey({ ...survey, introduction: e.target.value })}/></label>{questions.map((question, index) => <article key={question.id}><header><GripVertical/><Badge>{question.type}</Badge><strong>Question {index + 1}</strong><label className="required-toggle"><input type="checkbox" checked={question.required} onChange={(e) => setQuestions(questions.map((item) => item.id === question.id ? { ...item, required: e.target.checked } : item))}/> Required</label></header><textarea rows={2} value={question.question} onChange={(e) => setQuestions(questions.map((item) => item.id === question.id ? { ...item, question: e.target.value } : item))}/>{question.type !== "text" && <div className="editor-options">{(question.options_json ?? []).map((option, optionIndex) => <input key={optionIndex} value={option} onChange={(e) => setQuestions(questions.map((item) => item.id === question.id ? { ...item, options_json: (item.options_json ?? []).map((current, currentIndex) => currentIndex === optionIndex ? e.target.value : current) } : item))}/>)}</div>}</article>)}{error && <p className="form-error">{error}</p>}{saved && <p className="save-confirmation"><CheckCircle2/> Draft saved.</p>}<button className="button button-primary" onClick={save} disabled={busy}><Save size={16}/>{busy ? "Saving…" : "Save questionnaire draft"}</button></section></PageShell>;
}
