import { PageShell } from "@/components/page-shell";
import { AgentAvatar } from "@/components/agent-avatar";
import { Badge, Button, Progress } from "@/components/ui";
import { activities, agents, findings, sampleProject } from "@/lib/demo-data";
import { loadFieldworkContext } from "@/lib/fieldwork";
import { ArrowRight, CircleDollarSign } from "lucide-react";

export default async function CommandCentre({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (id !== "live") return <SampleCommandCentre/>;
  try {
    const context = await loadFieldworkContext();
    const [{ data: analysis }, { data: brief }] = await Promise.all([
      context.db.from("agent_tasks").select("status,progress,output_json").eq("project_id", context.projectId).eq("task_type", "integrated_analysis").maybeSingle(),
      context.db.from("research_briefs").select("version").eq("project_id", context.projectId).order("version", { ascending: false }).limit(1).maybeSingle(),
    ]);
    const practiceIds = new Set(context.participants.filter((participant) => String(participant.consent_source ?? "").includes("practice session")).map((participant) => participant.id));
    const completedInterviews = context.interviews.filter((item) => item.status === "complete" && !practiceIds.has(item.participant_id)).length;
    const surveyLive = context.survey?.status === "published";
    const phase = brief ? "Decision brief ready" : analysis?.status === "complete" ? "Integrated analysis ready" : context.instrumentTask ? "Primary research in the field" : context.state.status === "complete" ? "Primary research setup" : "Secondary research";
    const progress = brief ? 100 : analysis?.status === "complete" ? 88 : context.instrumentTask ? 68 : context.state.status === "complete" ? 48 : Math.max(15, Math.round((context.task.progress ?? 0) * .45));
    return <PageShell eyebrow="Live research command centre" title={context.project.title} description={context.project.business_question} actions={<Button href={brief ? "/projects/live/brief" : analysis ? "/projects/live/analysis" : "/projects/live/secondary-research"} variant="secondary">Open current work</Button>}><section className="command-hero"><div className="command-heading"><div><Badge tone="coral">{context.project.status}</Badge><h2>{phase}</h2><p>{brief ? "Marcus has prepared the current evidence-linked decision brief." : analysis ? "Sofia has integrated the evidence available at the current cutoff." : surveyLive ? "The public survey is live and Daniel’s assisted interview room is ready." : "The research team is preparing the next evidence gate."}</p></div><AgentAvatar slug={brief ? "marcus-lee" : analysis ? "sofia-tan" : context.instrumentTask ? "aisha-rahman" : "maya-chen"} size="lg"/></div><Progress value={progress}/><div className="command-metrics"><div><strong>{progress}%</strong><span>Engagement complete</span></div><div><strong>{context.state.sources.length}</strong><span>Sources retained</span></div><div><strong>{context.responses.length}</strong><span>Live survey responses</span></div><div><strong>{completedInterviews}</strong><span>Interviews completed</span></div></div></section><div className="workflow-grid"><WorkflowCard n="01" title="Plan" status="Approved" href="/projects/live/plan"/><WorkflowCard n="02" title="Evidence" status={context.state.status === "complete" ? "Complete" : "In progress"} href="/projects/live/secondary-research"/><WorkflowCard n="03" title="Survey" status={context.survey?.status ?? "Not generated"} href="/projects/live/survey"/><WorkflowCard n="04" title="Interviews" status={`${completedInterviews} complete`} href="/projects/live/interviews"/><WorkflowCard n="05" title="Analysis" status={analysis?.status ?? "Not started"} href="/projects/live/analysis"/><WorkflowCard n="06" title="Brief" status={brief ? `Version ${brief.version}` : "Not started"} href="/projects/live/brief"/></div></PageShell>;
  } catch (error) {
    return <PageShell eyebrow="Live research command centre" title="The engagement could not be loaded." description={error instanceof Error ? error.message : "Open the engagement from the plan approval flow."}><Button href="/projects/new">Start a research engagement</Button></PageShell>;
  }
}

function WorkflowCard({ n, title, status, href }: { n: string; title: string; status: string; href: string }) { return <a className="workflow-card" href={href}><span>{n}</span><h3>{title}</h3><Badge>{status}</Badge><ArrowRight/></a>; }

function SampleCommandCentre() { return <PageShell eyebrow="Sample engagement · Transparent demonstration" title="The research is ready for the field." description={sampleProject.question} actions={<Button href="/projects/northstar-cinemas/brief" variant="secondary">Read sample brief</Button>}><section className="command-hero"><div className="command-heading"><div><Badge tone="coral">{sampleProject.status}</Badge><h2>{sampleProject.phase}</h2><p>Maya’s retained sources are real examples; the survey view is explicitly synthetic until responses arrive, and Daniel’s practice interview is excluded from evidence.</p></div><AgentAvatar slug="aisha-rahman" size="lg"/></div><Progress value={72}/><div className="command-metrics"><div><strong>72%</strong><span>Sample journey shown</span></div><div><strong>8</strong><span>Sources retained</span></div><div><strong>0</strong><span>Live survey responses</span></div><div><strong>0</strong><span>Research interviews</span></div></div></section><div className="dashboard-grid"><section className="panel"><div className="panel-header"><h2>Sample engagement trace</h2><Badge>Evidence modes labelled</Badge></div><div className="activity-list">{activities.map((activity) => <a className="activity-item" href={activity.href} key={activity.action}><AgentAvatar slug={activity.agent} size="sm"/><div><p>{activity.action}</p><small>{agents.find((agent) => agent.slug === activity.agent)?.name} · {activity.time}</small></div><div className="activity-meta"><Badge tone={activity.status === "In progress" ? "coral" : "default"}>{activity.status}</Badge><ArrowRight/></div></a>)}</div></section><aside><section className="panel"><div className="panel-header"><h2>Try the live features</h2><Badge>Interactive sample</Badge></div><p>Complete the public survey, hear Daniel speak a practice interview question, and inspect how synthetic evidence is disclosed in analysis.</p><div className="stack-actions"><Button href="/projects/northstar-cinemas/survey" variant="secondary">Open survey workspace</Button><Button href="/projects/northstar-cinemas/interviews" variant="secondary">Open interview room</Button></div></section><section className="panel" style={{marginTop:20}}><CircleDollarSign/><h3>Illustrative usage</h3><p className="muted-copy">No participant recruitment, incentives or external spending occurred in this sample.</p></section></aside></div><section style={{marginTop:20}}><div className="panel-header"><h2>Current sample findings</h2><Button href="/projects/northstar-cinemas/analysis" variant="ghost">Open integrated analysis</Button></div><div className="grid-3">{findings.map((finding) => <article className="panel finding-card" key={finding.title}><Badge>{finding.type}</Badge><h3>{finding.title}</h3><p>{finding.text}</p><span className="evidence-link">{finding.evidence}</span></article>)}</div></section></PageShell>; }
