"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { PageShell } from "@/components/page-shell";
import { AgentAvatar } from "@/components/agent-avatar";
import { Badge, Button } from "@/components/ui";
import { CheckCircle2 } from "lucide-react";

type Plan={decisionStatement:string;objectives:string[];hypotheses:string[];secondaryWorkstreams:{title:string;evidenceExpected:string[]}[];evidenceGaps:string[];primaryMethodology:string;targetRespondents:string;sampleSizeRecommendation:string;timeline:string;estimatedOperationalCosts:string;deliverables:string[];limitations:string[]};
const demoPlan:Plan={decisionStatement:"Choose the location archetype most likely to produce sustainable attendance and contribution: a major heartland regional mall or a city-centre mall.",objectives:["Estimate drivers of cinema choice and repeat visitation.","Compare catchment, access, competition and positioning.","Understand differences between family, young-adult and occasion-led audiences."],hypotheses:["Heartland sites support higher repeat visitation through convenience.","City-centre sites support premium pricing and occasion visits.","Rent and direct competition may offset central demand advantages."],secondaryWorkstreams:[{title:"Population and catchment",evidenceExpected:["Catchment size","Household composition"]},{title:"Access and competition",evidenceExpected:["Journey time","Competing cinema supply"]}],evidenceGaps:["Willingness to travel by segment","Premium-format price elasticity"],primaryMethodology:"Consumer survey and seven semi-structured, consent-based browser interviews.",targetRespondents:"Recent cinema-goers aged 18+, weighted toward candidate catchments.",sampleSizeRecommendation:"n=150 for directional segment analysis; demo contains n=38.",timeline:"Fourteen working days",estimatedOperationalCosts:"Illustrative S$3,000 excluding respondent incentives and licensed data.",deliverables:["Evidence library","Integrated analysis","Decision-ready brief"],limitations:["Demo responses and transcripts are synthetic.","Live work requires candidate-site economics and a representative sample."]};

export default function PlanPage(){const {id}=useParams<{id:string}>();const [approved,setApproved]=useState(id==="northstar-cinemas");const [plan,setPlan]=useState<Plan>(demoPlan);const live=id==="live";useEffect(()=>{if(live){const stored=localStorage.getItem("field-signal-live-plan");if(stored)try{setPlan(JSON.parse(stored) as Plan)}catch{}}},[live]);return <PageShell eyebrow={`Research plan · ${live?"Live AI output":"Version 2 · Demo data"}`} title="A plan built around the decision." description="John has translated the business question into bounded workstreams, evidence gates and an approval-controlled fieldwork programme." actions={!live?<Button href="/projects/northstar-cinemas/secondary-research">View evidence</Button>:undefined}><div className="approval"><div style={{display:"flex",alignItems:"center",gap:12}}><CheckCircle2 color={approved?"var(--teal)":"var(--gold)"}/><div><strong>{approved?"Research plan approved":"Awaiting your approval"}</strong><br/><small>No external fieldwork begins without this approval.</small></div></div><button className="button button-secondary" onClick={()=>setApproved(!approved)}>{approved?"Request revision":"Approve plan"}</button></div><section className="panel" style={{marginTop:20}}><div className="panel-header"><div style={{display:"flex",gap:14,alignItems:"center"}}><AgentAvatar slug="john-lim"/><div><Badge>John Lim · AI Research Director</Badge><h2 style={{marginTop:8}}>Decision architecture</h2></div></div><Badge tone={live?"default":"coral"}>{live?"Hugging Face output":"Demonstration engagement"}</Badge></div><PlanSection title="Decision statement"><p>{plan.decisionStatement}</p></PlanSection><PlanSection title="Research objectives"><List items={plan.objectives}/></PlanSection><PlanSection title="Working hypotheses"><List items={plan.hypotheses}/></PlanSection><PlanSection title="Secondary workstreams"><ul>{plan.secondaryWorkstreams.map(w=><li key={w.title}><strong>{w.title}:</strong> {w.evidenceExpected.join(", ")}</li>)}</ul></PlanSection><PlanSection title="Evidence gaps"><List items={plan.evidenceGaps}/></PlanSection><PlanSection title="Primary methodology"><p>{plan.primaryMethodology}</p><p><strong>Respondents:</strong> {plan.targetRespondents}</p><p><strong>Sample:</strong> {plan.sampleSizeRecommendation}</p></PlanSection><PlanSection title="Timeline & costs"><p>{plan.timeline}. {plan.estimatedOperationalCosts}</p></PlanSection><PlanSection title="Deliverables"><List items={plan.deliverables}/></PlanSection><PlanSection title="Limitations"><List items={plan.limitations}/></PlanSection></section></PageShell>}
function PlanSection({title,children}:{title:string;children:React.ReactNode}){return <div className="plan-section"><h3>{title}</h3><div>{children}</div></div>}
function List({items}:{items:string[]}){return <ul>{items.map(item=><li key={item}>{item}</li>)}</ul>}
