create extension if not exists pgcrypto;

create table profiles (id uuid primary key references auth.users on delete cascade, email text, full_name text, created_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table agents (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, role text not null, biography text not null, specialisation text not null, avatar_path text, colour text not null, is_ai boolean not null default true);
create table research_projects (id uuid primary key default gen_random_uuid(), owner_id uuid references profiles(id) on delete cascade, title text not null, business_question text not null, business_description text, industry text, geography text, research_mode text not null check(research_mode in ('secondary','primary_secondary')), objective text, budget numeric, deadline date, status text not null default 'draft', current_phase text not null default 'intake', demo_mode boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(owner_id is not null or demo_mode));
create table clarifying_questions (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, agent_id uuid references agents, question text not null, answer text, position int not null);
create table research_plans (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, version int not null default 1, structured_plan_json jsonb not null, status text not null default 'draft', approved_at timestamptz, created_at timestamptz not null default now(), unique(project_id,version));
create table agent_tasks (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, agent_id uuid not null references agents, task_type text not null, title text not null, description text, status text not null default 'queued', progress int not null default 0 check(progress between 0 and 100), output_json jsonb, started_at timestamptz, completed_at timestamptz);
create table sources (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, title text not null, publisher text, url text, publication_date date, retrieved_at timestamptz not null default now(), excerpt text, supported_claim text, reliability_note text);
create table surveys (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, title text not null, introduction text, public_token text unique not null default encode(gen_random_bytes(24),'hex'), status text not null default 'draft', published_at timestamptz);
create table survey_questions (id uuid primary key default gen_random_uuid(), survey_id uuid not null references surveys on delete cascade, type text not null check(type in ('single','multiple','rating','text')), question text not null, options_json jsonb, required boolean not null default false, position int not null);
create table survey_responses (id uuid primary key default gen_random_uuid(), survey_id uuid not null references surveys on delete cascade, consented_at timestamptz not null, completed_at timestamptz, respondent_metadata_json jsonb not null default '{}');
create table survey_answers (id uuid primary key default gen_random_uuid(), response_id uuid not null references survey_responses on delete cascade, question_id uuid not null references survey_questions, answer_json jsonb not null);
create table interview_participants (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, name text, email_or_phone text, consent_source text, public_token text unique not null default encode(gen_random_bytes(24),'hex'), status text not null default 'invited');
create table interviews (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, participant_id uuid not null references interview_participants on delete cascade, status text not null default 'awaiting_consent', consented_at timestamptz, started_at timestamptz, completed_at timestamptz, summary text, themes_json jsonb);
create table interview_messages (id uuid primary key default gen_random_uuid(), interview_id uuid not null references interviews on delete cascade, speaker text not null check(speaker in ('agent','participant','system')), content text not null, created_at timestamptz not null default now());
create table research_findings (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, agent_id uuid references agents, finding_type text not null, title text not null, summary text not null, confidence text not null, evidence_links_json jsonb not null default '[]');
create table research_briefs (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, version int not null default 1, content_json jsonb not null, created_at timestamptz not null default now());
create table agent_activity (id uuid primary key default gen_random_uuid(), project_id uuid not null references research_projects on delete cascade, agent_id uuid references agents, action text not null, status text not null, metadata_json jsonb not null default '{}', created_at timestamptz not null default now());

create index on research_projects(owner_id); create index on sources(project_id); create index on survey_responses(survey_id); create index on interview_messages(interview_id); create index on agent_activity(project_id,created_at desc);

alter table profiles enable row level security; alter table research_projects enable row level security; alter table clarifying_questions enable row level security; alter table research_plans enable row level security; alter table agent_tasks enable row level security; alter table sources enable row level security; alter table surveys enable row level security; alter table survey_questions enable row level security; alter table survey_responses enable row level security; alter table survey_answers enable row level security; alter table interview_participants enable row level security; alter table interviews enable row level security; alter table interview_messages enable row level security; alter table research_findings enable row level security; alter table research_briefs enable row level security; alter table agent_activity enable row level security;

create policy "own profile" on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "owners manage projects" on research_projects for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create or replace function owns_project(pid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from research_projects where id=pid and owner_id=auth.uid()) $$;
create policy "owners manage questions" on clarifying_questions for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage plans" on research_plans for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage tasks" on agent_tasks for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage sources" on sources for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage surveys" on surveys for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage questions by survey" on survey_questions for all using(exists(select 1 from surveys s where s.id=survey_id and owns_project(s.project_id)));
create policy "owners read responses" on survey_responses for select using(exists(select 1 from surveys s where s.id=survey_id and owns_project(s.project_id)));
create policy "owners read answers" on survey_answers for select using(exists(select 1 from survey_responses r join surveys s on s.id=r.survey_id where r.id=response_id and owns_project(s.project_id)));
create policy "owners manage participants" on interview_participants for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage interviews" on interviews for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners read messages" on interview_messages for select using(exists(select 1 from interviews i where i.id=interview_id and owns_project(i.project_id)));
create policy "owners manage findings" on research_findings for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners manage briefs" on research_briefs for all using(owns_project(project_id)) with check(owns_project(project_id));
create policy "owners read activity" on agent_activity for select using(owns_project(project_id));

-- Public writes are handled by token-validating server routes using the service role.
-- No anonymous table policy exposes participant records, answers, transcripts, or private projects.
