"use client";

import { useCallback, useEffect, useState } from "react";
import { AgentAvatar } from "@/components/agent-avatar";
import { BriefGenerationStatus } from "@/components/brief-generation-status";
import { PageShell } from "@/components/page-shell";
import { PrintButton } from "@/components/print-button";
import { Badge } from "@/components/ui";
import { AlertTriangle, CheckCircle2, FileText, Link2, RefreshCw, Sparkles } from "lucide-react";

type Brief = { title: string; executiveRecommendation: string; rationale: string[]; evidenceSummary: { claim: string; support: string; evidenceIds: string[] }[]; risks: string[]; changeConditions: string[]; nextActions: string[]; methodology: string; limitations: string[]; dataMode?: string; liveResponseCount?: number; syntheticResponseCount?: number; completedInterviews?: number; secondarySourceCount?: number; dataCutoff?: string };
const demoBrief: Brief = { title: "Northstar Cinemas location decision brief", executiveRecommendation: "Do not select a location archetype yet. Prioritise candidate-site economics and collect live customer evidence before committing; published evidence currently makes the heartland case more resilient, but does not establish site-level returns.", rationale: ["Available sources make access and repeatable visit occasions material to the decision.", "The heartland hypothesis appears less dependent on weekday office traffic.", "The current survey view is synthetic and therefore cannot validate customer preference."], evidenceSummary: [{ claim: "Convenience is decision-relevant", support: "Multiple retained published sources connect access and trip convenience with repeat visitation.", evidenceIds: ["S01", "S04", "S06"] }, { claim: "Primary preference remains unverified", support: "No genuine survey responses or completed research interviews were available at the cutoff.", evidenceIds: ["synthetic-q2"] }], risks: ["Candidate rents may reverse the location-level economics.", "No live primary sample currently validates the preference hypotheses."], changeConditions: ["A CBD candidate with materially stronger unit economics", "Live evidence showing reliable willingness to travel for the CBD offer"], nextActions: ["Share the published survey and collect an initial live base.", "Run assisted interviews with recent cinema-goers.", "Compare actual candidate rent, footfall and day-part assumptions."], methodology: "Integrated review of eight retained secondary sources plus a clearly labelled synthetic survey preview. No completed interview evidence was included.", limitations: ["Synthetic survey responses are interface demonstrations, not market evidence.", "Published evidence cannot replace candidate-site commercial due diligence."], dataMode: "synthetic", liveResponseCount: 0, syntheticResponseCount: 48, completedInterviews: 0, secondarySourceCount: 8 };

export function BriefWorkspace({ demo }: { demo: boolean }) {
  const [brief, setBrief] = useState<Brief | null>(demo ? demoBrief : null); const [version, setVersion] = useState(demo ? 1 : 0); const [analysisReady, setAnalysisReady] = useState(demo); const [stale, setStale] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (demo) return; const response = await fetch("/api/brief", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setBrief(result.brief); setVersion(result.version); setStale(result.stale); setAnalysisReady(result.analysisReady); }, [demo]);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function generate() { setBusy(true); setError(""); try { const response = await fetch("/api/brief", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Brief generation failed"); } finally { setBusy(false); } }
  return <PageShell eyebrow={demo ? "Sample decision brief · Version 1" : `Decision brief${version ? ` · Version ${version}` : ""}`} title="A recommendation you can interrogate." description="Marcus converts Sofia’s persisted findings into a concise decision brief, carrying evidence IDs, uncertainty and the conditions that could change the recommendation.">
    {error && <div className="notice form-error">{error}</div>}{stale && <div className="synthetic-banner"><RefreshCw/><div><Badge tone="gold">New evidence available</Badge><p>This brief predates the latest analysis. Regenerate it before relying on the recommendation.</p></div></div>}
    {busy ? <BriefGenerationStatus/> : !brief ? <section className="panel fieldwork-empty"><AgentAvatar slug="marcus-lee" size="lg"/><FileText/><h2>{analysisReady ? "The analysis is ready for Marcus." : "Complete Sofia’s analysis first."}</h2><p>{analysisReady ? "Marcus will prepare a versioned brief from persisted findings—not from untraceable model context." : "The brief remains locked until a current integrated analysis exists."}</p><button className="button button-primary" disabled={!analysisReady} onClick={generate}><Sparkles size={16}/> Generate decision brief</button></section> : <article className="brief-document"><header><div className="agent-inline"><AgentAvatar slug="marcus-lee"/><div><Badge>Prepared by Marcus Lee · AI Strategy Consultant</Badge><h1>{brief.title}</h1></div></div><div className="brief-actions"><PrintButton/>{!demo && <button className="button button-secondary" onClick={generate}><RefreshCw size={16}/> Regenerate</button>}</div></header>{brief.dataMode === "synthetic" && <div className="brief-disclosure"><AlertTriangle/><p><strong>Synthetic survey disclosure.</strong> No live survey response was available at the analysis cutoff. Synthetic survey material demonstrates the workflow and is not treated as customer evidence.</p></div>}<section className="brief-recommendation"><span>Executive recommendation</span><h2>{brief.executiveRecommendation}</h2></section><BriefSection n="01" title="Why this direction"><ul>{brief.rationale.map((item) => <li key={item}>{item}</li>)}</ul></BriefSection><BriefSection n="02" title="Evidence behind the recommendation"><div className="evidence-table">{brief.evidenceSummary.map((item) => <div key={item.claim}><h3>{item.claim}</h3><p>{item.support}</p><span>{item.evidenceIds.map((id) => <Badge key={id}><Link2 size={10}/>{id}</Badge>)}</span></div>)}</div></BriefSection><div className="grid-2"><BriefSection n="03" title="Risks"><ul>{brief.risks.map((item) => <li key={item}>{item}</li>)}</ul></BriefSection><BriefSection n="04" title="What would change the view"><ul>{brief.changeConditions.map((item) => <li key={item}>{item}</li>)}</ul></BriefSection></div><BriefSection n="05" title="Recommended next actions"><ol>{brief.nextActions.map((item) => <li key={item}>{item}</li>)}</ol></BriefSection><BriefSection n="06" title="Methodology and limitations"><p>{brief.methodology}</p><ul>{brief.limitations.map((item) => <li key={item}>{item}</li>)}</ul><div className="brief-bases"><Badge>{brief.secondarySourceCount ?? 0} secondary sources</Badge><Badge>{brief.liveResponseCount ?? 0} live survey responses</Badge><Badge>{brief.completedInterviews ?? 0} completed interviews</Badge>{brief.syntheticResponseCount ? <Badge tone="coral">Synthetic preview n={brief.syntheticResponseCount}</Badge> : null}</div></BriefSection><footer><CheckCircle2/><span>Evidence-linked brief · Version {version} · {brief.dataCutoff ? new Date(brief.dataCutoff).toLocaleString() : "Sample cutoff"}</span></footer></article>}
  </PageShell>;
}
function BriefSection({ n, title, children }: { n: string; title: string; children: React.ReactNode }) { return <section className="brief-section"><span>{n}</span><div><h2>{title}</h2>{children}</div></section>; }
