import { PageShell } from "@/components/page-shell";
import { Badge, Button } from "@/components/ui";
import { AgentAvatar } from "@/components/agent-avatar";
import { PrintButton } from "@/components/print-button";
import { Link2 } from "lucide-react";

export default function Brief(){return <PageShell eyebrow="Strategic brief · Version 1 · Demo data" title="A recommendation you can interrogate." description="Every major claim links back to the evidence trail. Print this view to export a clean PDF from your browser." actions={<><PrintButton/><Button href="/projects/northstar-cinemas/command-centre" variant="secondary">Command centre</Button></>}><article className="brief">
  <div className="brief-cover"><div><Badge tone="coral">Demonstration brief · Not investment advice</Badge><h1>Northstar Cinemas:<br/>next-location strategy</h1></div><div><p>Prepared by Field & Signal’s autonomous research team</p><p>15 July 2026 · Singapore</p></div></div>
  <BriefSection n="01" title="Executive recommendation"><p className="recommendation">Prioritise a major heartland regional centre for repeat visitation and family demand, subject to rental and catchment validation.</p><div className="confidence"><span/><span/><span/><span/></div><small>Directional confidence: medium-high within the illustrative evidence; not valid for a live investment decision.</small></BriefSection>
  <BriefSection n="02" title="Decision context"><p>Northstar is choosing between two location archetypes for its next Singapore outlet: a heartland regional mall and a city-centre mall. The decision optimises sustainable attendance and contribution, not opening-week traffic alone.</p></BriefSection>
  <BriefSection n="03" title="Methodology"><p>This demonstration combines a labelled desk-research dataset, 38 synthetic survey responses and five synthetic interview transcripts. No real respondents were contacted. A live engagement would validate URLs, recruit a representative sample and incorporate candidate-site economics.</p></BriefSection>
  <BriefSection n="04" title="Why heartland leads"><ul><li><strong>Repeat convenience:</strong> travel time is a top-two driver for 29 of 38 demo respondents. <Evidence>Survey Q2</Evidence></li><li><strong>Family fit:</strong> family respondents describe combining cinema visits with meals and errands. <Evidence>Interviews I02, I04</Evidence></li><li><strong>Catchment:</strong> the illustrative 20-minute model favours regional centres. <Evidence>Source S05</Evidence></li></ul></BriefSection>
  <BriefSection n="05" title="What central does better"><p>City-centre sites hold stronger premium and occasion cues, especially among younger adults and date-night users. That advantage may support differentiated formats but appears less connected to frequent visitation in this demo.</p><Evidence>Interviews I01, I05 · Survey Q4 · Source S04</Evidence></BriefSection>
  <BriefSection n="06" title="Risks & conditions"><ul><li>The recommendation changes if regional rent savings are negligible or catchment overlap is high.</li><li>A central site may win if Northstar prioritises premium flagship positioning over frequency.</li><li>The small synthetic sample cannot estimate demand or revenue.</li><li>Competitor openings and candidate-level access must be revalidated.</li></ul></BriefSection>
  <BriefSection n="07" title="Next actions"><ol><li>Shortlist two candidate regional centres and one central comparator.</li><li>Obtain rental, footfall and catchment data under NDA.</li><li>Run a representative n≥150 demand survey with site stimuli.</li><li>Build a unit-economics model and specify go/no-go thresholds.</li></ol></BriefSection>
  <div style={{display:"flex",gap:16,alignItems:"center",marginTop:50,paddingTop:30,borderTop:"1px solid var(--line)"}}><AgentAvatar slug="marcus-lee" size="lg"/><div><Badge>Marcus Lee · AI Strategy Consultant</Badge><p style={{margin:"10px 0 0"}}>Synthesised from the supplied evidence under John Lim’s approved research plan.</p></div></div>
</article></PageShell>}
function BriefSection({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="brief-section"><h2>{n}<br/>{title}</h2><div>{children}</div></section>}
function Evidence({children}:{children:React.ReactNode}){return <span className="evidence-link"><Link2 size={11} style={{display:"inline"}}/> {children}</span>}
