"use client";

import { useCallback, useEffect, useState } from "react";
import { AgentAvatar } from "@/components/agent-avatar";
import { PageShell } from "@/components/page-shell";
import { Badge, Button, Progress } from "@/components/ui";
import { AlertTriangle, BarChart3, GitCompareArrows, Link2, Sparkles } from "lucide-react";

type Finding = { type: string; title: string; observation: string; interpretation: string; implication: string; confidence: "High" | "Medium" | "Directional"; evidenceIds: string[]; limitations: string[] };
type Analysis = { overview: string; findings: Finding[]; agreements: string[]; contradictions: string[]; remainingGaps: string[]; dataMode: "live" | "synthetic" | "not_applicable"; liveResponseCount: number; syntheticResponseCount: number; completedInterviews: number; secondarySourceCount: number; dataCutoff?: string };
type Snapshot = { status: string; progress: number; analysis: Analysis | null; evidence: { survey: { mode: string; liveResponseCount: number; syntheticResponseCount: number }; completedInterviews: number; secondarySources: number } };
const demoAnalysis: Analysis = { overview: "Published evidence suggests access and visit occasion matter, while the synthetic survey preview illustrates how preference patterns will be presented once live respondents participate.", dataMode: "synthetic", liveResponseCount: 0, syntheticResponseCount: 48, completedInterviews: 0, secondarySourceCount: 8, findings: [{ type: "secondary", title: "Convenience is likely to shape repeatability", observation: "Available location and consumer sources consistently identify access and trip convenience as relevant to repeat visits.", interpretation: "A heartland venue may fit more routine, multi-purpose trips, while a CBD venue may depend more heavily on weekday occasions.", implication: "Compare candidate-site access and day-part economics before selecting a location type.", confidence: "Medium", evidenceIds: ["S01", "S04", "S06"], limitations: ["Published evidence does not establish site-level revenue."] }, { type: "survey", title: "Survey pattern is illustrative only", observation: "A synthetic n=48 preview shows how location preferences could be segmented.", interpretation: "It demonstrates the analysis interface, not a customer conclusion.", implication: "Share the live survey before relying on primary evidence.", confidence: "Directional", evidenceIds: ["synthetic-q2"], limitations: ["No genuine survey responses have been collected."] }], agreements: ["Secondary sources consistently make access a decision-relevant factor."], contradictions: ["No live primary evidence is available to confirm or challenge published patterns."], remainingGaps: ["Live customer preferences", "Candidate-site rent and unit economics", "Completed interview explanations"] };

export function AnalysisWorkspace({ demo }: { demo: boolean }) {
  const [data, setData] = useState<Snapshot>(demo ? { status: "complete", progress: 100, analysis: demoAnalysis, evidence: { survey: { mode: "synthetic", liveResponseCount: 0, syntheticResponseCount: 48 }, completedInterviews: 0, secondarySources: 8 } } : { status: "loading", progress: 15, analysis: null, evidence: { survey: { mode: "unknown", liveResponseCount: 0, syntheticResponseCount: 0 }, completedInterviews: 0, secondarySources: 0 } });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (demo) return; const response = await fetch("/api/analysis", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); }, [demo]);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  async function run() { setBusy(true); setError(""); try { const response = await fetch("/api/analysis", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Analysis failed"); } finally { setBusy(false); } }
  const analysis = data.analysis;
  return <PageShell eyebrow={demo ? "Sample integrated analysis" : "Integrated analysis · Evidence linked"} title="What the evidence says—together." description="Sofia calculates the survey results in code, then compares them with Maya’s sources and completed interview transcripts. Missing evidence remains visibly missing.">
    {error && <div className="notice form-error">{error}</div>}
    <section className="analysis-hero panel"><div className="agent-inline"><AgentAvatar slug="sofia-tan" size="lg"/><div><Badge>Sofia Tan · AI Insights Analyst</Badge><h2>{busy ? "Integrating the evidence" : analysis ? "Integrated evidence review" : "Ready to analyse current evidence"}</h2><p>{busy ? "Sofia is calculating bases, comparing evidence streams and checking every claim against a source ID." : analysis?.overview ?? "Run the analysis whenever you want a decision view of the evidence currently available."}</p></div></div>{busy ? <div className="analysis-progress"><Progress value={72}/><span>Survey calculations complete · comparing evidence streams</span></div> : <button className="button button-primary" onClick={run} disabled={demo}><Sparkles size={16}/>{analysis ? "Refresh analysis with latest evidence" : "Analyse current evidence"}</button>}</section>
    <div className="grid-4"><div className="metric"><strong>{analysis?.secondarySourceCount ?? data.evidence.secondarySources}</strong><span>Secondary sources</span></div><div className="metric"><strong>{analysis?.liveResponseCount ?? data.evidence.survey.liveResponseCount}</strong><span>Live survey responses</span><small>Never mixed with synthetic</small></div><div className="metric"><strong>{analysis?.completedInterviews ?? data.evidence.completedInterviews}</strong><span>Completed interviews</span></div><div className="metric"><strong>{analysis?.dataMode === "synthetic" ? `Synthetic n=${analysis.syntheticResponseCount}` : analysis?.dataMode === "not_applicable" ? "Not included" : "Live only"}</strong><span>Survey analysis mode</span></div></div>
    {analysis?.dataMode === "synthetic" && <div className="synthetic-banner"><AlertTriangle/><div><Badge tone="coral">Synthetic survey demonstration</Badge><p>No genuine survey response was available at this cutoff. Survey charts and survey-based findings are illustrative, visibly labelled and excluded as market proof. Secondary evidence remains real.</p></div></div>}
    {!analysis ? <section className="panel fieldwork-empty"><BarChart3/><h2>No integrated analysis yet.</h2><p>Sofia will use the evidence available now. If there are no survey responses, she will create a separately labelled synthetic preview; she will never invent interviews.</p></section> : <><div className="grid-3 analysis-findings">{analysis.findings.map((finding) => <article className="panel finding-card" key={finding.title}><div className="finding-badges"><Badge>{finding.type}</Badge><Badge tone={finding.confidence === "High" ? "default" : finding.confidence === "Medium" ? "gold" : "coral"} title={finding.confidence === "High" ? "Convergent, directly relevant evidence." : finding.confidence === "Medium" ? "Useful evidence with material limitations." : "An early indication that needs validation."}>{finding.confidence} confidence</Badge></div><h3>{finding.title}</h3><p><strong>Observation.</strong> {finding.observation}</p><p><strong>Interpretation.</strong> {finding.interpretation}</p><p><strong>Decision implication.</strong> {finding.implication}</p><div className="evidence-chips">{finding.evidenceIds.map((id) => <Badge key={id}><Link2 size={11}/>{id}</Badge>)}</div>{finding.limitations.length > 0 && <small className="limitation">Limit: {finding.limitations.join(" ")}</small>}</article>)}</div><div className="grid-2"><section className="panel"><GitCompareArrows/><h2>Where evidence agrees</h2>{analysis.agreements.map((item) => <p key={item}>• {item}</p>)}</section><section className="panel"><AlertTriangle/><h2>Contradictions and gaps</h2>{[...analysis.contradictions, ...analysis.remainingGaps].map((item) => <p key={item}>• {item}</p>)}</section></div><div className="analysis-next"><small>Data cutoff: {analysis.dataCutoff ? new Date(analysis.dataCutoff).toLocaleString() : "Sample engagement"}</small><Button href="/projects/live/brief">Ask Marcus to prepare the brief</Button></div></>}
  </PageShell>;
}
