"use client";

import { useState } from "react";
import { Logo } from "@/components/logo";
import { Badge, Progress } from "@/components/ui";
import { CheckCircle2, ChevronLeft, ChevronRight, ShieldCheck } from "lucide-react";

type Question = { id: string; type: "single" | "multiple" | "rating" | "text"; question: string; options_json?: string[]; required: boolean; position: number };
export function PublicSurvey({ token, demo = false, survey }: { token: string; demo?: boolean; survey: { title: string; introduction: string; projectTitle: string; estimatedMinutes: number; questions: Question[] } }) {
  const [consent, setConsent] = useState(false); const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string, string | string[]>>({}); const [done, setDone] = useState(false); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const question = survey.questions[index]; const key = `q${question?.position}`;
  function answer(value: string, checked?: boolean) { if (question.type === "multiple") { const current = Array.isArray(answers[key]) ? answers[key] as string[] : []; setAnswers({ ...answers, [key]: checked ? [...current, value] : current.filter((v) => v !== value) }); } else setAnswers({ ...answers, [key]: value }); }
  function canContinue() { if (!question.required) return true; const value = answers[key]; return Array.isArray(value) ? value.length > 0 : Boolean(value?.trim()); }
  async function submit() { if (!canContinue()) { setError("Please answer this required question before continuing."); return; } setSubmitting(true); setError(""); try { if (!demo) { const storageKey=`field-signal-response-${token}`;let responseKey=localStorage.getItem(storageKey);if(!responseKey){responseKey=crypto.randomUUID();localStorage.setItem(storageKey,responseKey)}const response = await fetch("/api/survey-responses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, consent: true, responseKey, answers }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); } setDone(true); } catch (e) { setError(e instanceof Error ? e.message : "We could not record that response."); } finally { setSubmitting(false); } }
  if (done) return <main className="app-page"><div className="public-study-shell"><Logo/><section className="panel completion-card"><CheckCircle2 size={48}/><Badge>{demo ? "Practice response complete" : "Response recorded"}</Badge><h1>Thank you.</h1><p>{demo ? "This was a sample survey, so your answers were not added to a live research dataset." : "Your response is now part of this study. You may close this page."}</p></section></div></main>;
  return <main className="app-page"><div className="public-study-shell"><Logo/><section className="panel public-study-card"><Badge tone="coral">{survey.projectTitle} · Research study</Badge><h1>{survey.title}</h1><p>{survey.introduction}</p>{!started ? <><div className="consent-box"><ShieldCheck/><h3>Your choice, throughout</h3><p>This study takes about {survey.estimatedMinutes} minutes. Field & Signal uses AI research agents. Your answers will be analysed only for the stated research purpose. Avoid including unnecessary personal information; you may stop at any time.</p><label><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)}/> I am 18 or older and consent to participate.</label></div><button className="button button-primary" disabled={!consent} onClick={() => setStarted(true)}>Begin survey <ChevronRight size={17}/></button></> : <><div className="survey-progress"><span>Question {index + 1} of {survey.questions.length}</span><span>{Math.round(((index + 1) / survey.questions.length) * 100)}%</span></div><Progress value={((index + 1) / survey.questions.length) * 100}/><article className="public-question"><Badge>{question.type}</Badge><h2>{question.question}{question.required && <b className="required"> *</b>}</h2>{question.type === "text" ? <textarea autoFocus rows={5} value={String(answers[key] ?? "")} onChange={(e) => answer(e.target.value)} placeholder="Type your answer"/> : <div className="public-options">{(question.options_json ?? []).map((option) => <label key={option}><input type={question.type === "multiple" ? "checkbox" : "radio"} checked={question.type === "multiple" ? (Array.isArray(answers[key]) && (answers[key] as string[]).includes(option)) : answers[key] === option} onChange={(e) => answer(option, e.target.checked)}/><span>{option}</span></label>)}</div>}</article>{error && <p role="alert" className="form-error">{error}</p>}<div className="survey-buttons"><button className="button button-secondary" disabled={index === 0} onClick={() => { setError(""); setIndex(index - 1); }}><ChevronLeft size={17}/> Previous</button>{index < survey.questions.length - 1 ? <button className="button button-primary" onClick={() => { if (!canContinue()) return setError("Please answer this required question before continuing."); setError(""); setIndex(index + 1); }}>Next <ChevronRight size={17}/></button> : <button className="button button-primary" disabled={submitting} onClick={submit}>{submitting ? "Recording…" : "Submit response"}</button>}</div></>}</section></div></main>;
}
