"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import { Logo } from "@/components/logo";
import { Badge } from "@/components/ui";
import { surveyQuestions } from "@/lib/demo-data";
import { CheckCircle2, ShieldCheck } from "lucide-react";

export function PublicSurvey(){
  const params=useParams<{publicToken:string}>(); const [consent,setConsent]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const keys=[...new Set([...form.keys()])];const answers=Object.fromEntries(keys.map(key=>{const values=form.getAll(key).map(String);return [key,values.length>1?values:values[0]]}));const response=await fetch("/api/survey-responses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:params.publicToken,consent:true,answers})});if(response.ok)setDone(true);else setError("We could not record that response. Please try again.")}
  if(done)return <main className="app-page"><div className="panel" style={{maxWidth:650,margin:"60px auto",textAlign:"center",padding:50}}><CheckCircle2 size={44} style={{margin:"auto auto 20px",color:"var(--teal)"}}/><h1 style={{font:"500 48px var(--font-serif)"}}>Thank you.</h1><p>Your response has been recorded. In demo mode it is accepted locally and clearly kept separate from the seeded result charts.</p></div></main>;
  return <main className="app-page"><div style={{maxWidth:760,margin:"20px auto"}}><Logo/><div className="panel" style={{marginTop:32,padding:40}}><Badge tone="coral">Northstar Cinemas · Demonstration study</Badge><h1 style={{font:"500 54px/1 var(--font-serif)",margin:"20px 0"}}>Help us understand how people choose a cinema.</h1><p style={{lineHeight:1.65}}>This short study takes about four minutes. Your answers support research into cinema location preferences. The study is a hackathon demonstration and does not represent live commercial research.</p><div className="notice"><ShieldCheck size={18}/><strong> Research consent</strong><p>Your answers will be used only for this stated research purpose. Avoid sharing personal information. You may skip optional questions or stop at any time.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I am 18 or older and consent to participate.</label></div>{consent&&<form onSubmit={submit} style={{marginTop:30}}>{surveyQuestions.map((q,i)=><div className="question-card" key={q.id}><p>{i+1}. {q.question} {q.required&&<span style={{color:"var(--coral)"}}>*</span>}</p>{q.type==="text"?<textarea name={q.id} aria-label={q.question} rows={3} style={{width:"100%"}}/>:<div style={{display:"grid",gap:8}}>{q.options?.map(o=><label key={o}><input value={o} required={q.required} type={q.type==="multiple"?"checkbox":"radio"} name={q.id}/> {o}</label>)}</div>}</div>)}{error&&<p role="alert" style={{color:"var(--coral)"}}>{error}</p>}<button className="button button-primary" type="submit">Submit response</button></form>}</div></div></main>
}
